<a href="https://colab.research.google.com/github/HarshRaj3112007/100-Days-of-ML/blob/main/KNN_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [3]:
df

      Age  Pclass     Fare  Survived
0    22.0       3   7.2500         0
1    38.0       1  71.2833         1
2    26.0       3   7.9250         1
3    35.0       1  53.1000         1
4    35.0       3   8.0500         0
..    ...     ...      ...       ...
886  27.0       2  13.0000         0
887  19.0       1  30.0000         1
888   NaN       3  23.4500         0
889  26.0       1  30.0000         1
890  32.0       3   7.7500         0

[891 rows x 4 columns]

In [4]:
df.isnull().sum()

Age         177
Pclass        0
Fare          0
Survived      0
dtype: int64

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [9]:
knn = KNNImputer(n_neighbors=3,weights='distance')
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.fit_transform(X_test)

In [13]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)
y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.6983240223463687

In [11]:
si = SimpleImputer()
si_train = si.fit_transform(X_train)
si_test = si.transform(X_test)

In [12]:
lr2 = LogisticRegression()

lr2.fit(si_train,y_train)
y_pred2 = lr2.predict(si_test)

accuracy_score(y_test,y_pred2)

0.6927374301675978